# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LazyA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  use_frameworks!
pod 'Charts', '~> 3.0.1'
pod 'RealmSwift', '~> 3.4.0'
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end

  # Pods for LazyA

  target 'LazyATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LazyAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
