# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LazyA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
pod 'Charts'
  use_frameworks!

  # Pods for LazyA

  target 'LazyATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LazyAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
